GET http://localhost:4000/ping


###
GET http://localhost:4000/events


###
GET http://localhost:4000/events/e334aad1-2121-4133-b1e7-8f70322f2b46


###
GET http://localhost:4000/events/validate/evento-fullstack/809xoae2dmv-tuad9sr7ce-vw7ysr1egy