@hostname = 127.0.0.1
@port = 4000
@event-slug = casamento-alberto-marina
@event-id = 20449a23-79b7-4cbe-a85c-99063af3dd22

###
GET http://{{ hostname }}:{{ port }}/events

###
GET http://{{ hostname }}:{{ port }}/events/{{ event-slug }}

###
GET http://{{ hostname }}:{{ port }}/events/{{ event-id }}


###
GET http://{{ hostname }}:{{ port }}/events/validation/inauguracao-loja-estrela/c9b68f49-64fe-487b-abf0-877ff0556891


###
GET http://{{ hostname }}:{{ port }}/events/validation/inauguracao-loja-estrela/{{ event-id }}


###
POST http://{{ hostname }}:{{ port }}/events/access
Content-Type: application/json

{
  "id": "{{ event-id }}",
  "password": "front123"
}

###
POST http://{{ hostname }}:{{ port }}/events/{{ event-slug }}/guest
Content-Type: application/json

{
  "guest": {
    "id": "7e2d9640-480b-43c8-8e15-bc6f0d70c68d",
    "name": "Cláudia Lima",
    "email": "claudia@example.com",
    "confirmation": true,
    "hasCompanions": true,
    "quantityCompanions": 3
  }
}

####
POST http://{{ hostname }}:{{ port }}/events/
Content-Type: application/json

{
  "event": {
    "password": "formacao123",
    "name": "Evento Semana Formação .DEV",
    "slug": "semana-formacao-dev",
    "date": "2024-11-30T09:00:00Z",
    "location": "Novo Horizonte, MG",
    "description": "Aprenda a criar interfaces incríveis e responsivas.",
    "image": "https://www.simplilearn.com/ice9/free_resources_article_thumb/recact_angular_vue.jpg",
    "bgImage": "https://www.frontendmag.com/wp-content/uploads/2023/01/easiest-front-end-framework.jpeg",
    "expectedAudience": 150
  }
}