# @hostname = 10.22.54.2
@hostname = 127.0.0.1
@port = 4000
@event-slug = casamento-alberto-marina
@event-id = a83e31ce-ba20-4267-8293-99dbd87c8726

###
GET http://{{ hostname }}:{{ port }}/events

###
GET http://{{ hostname }}:{{ port }}/events/{{ event-slug }}

###
GET http://{{ hostname }}:{{ port }}/events/{{ event-id }}


###
GET http://{{ hostname }}:{{ port }}/events/validation/inauguracao-loja-estrela/c9b68f49-64fe-487b-abf0-877ff0556891


###
GET http://{{ hostname }}:{{ port }}/events/validation/inauguracao-loja-estrela/{{ event-id }}


###
POST http://{{ hostname }}:{{ port }}/events/access
Content-Type: application/json

{
  "id": "{{ event-id }}",
  "password": "password123"
}

###
POST http://{{ hostname }}:{{ port }}/events/{{ event-slug }}/guest
Content-Type: application/json

{
  "guest": {
    "name": "Ricardo Pereira",
    "email": "patrese@example.com",
    "confirmation": true,
    "hasCompanions": true,
    "quantityCompanions": 3
  }
}

####
POST http://{{ hostname }}:{{ port }}/events
Content-Type: application/json

{
    "slug" : "evento-qualquer",
    "password" : "qualquer123",
    "name" : "Evento Qualquer Coisa",
    "date" : "2024-11-30T06:00",
    "location" : "Novo Horizonte - SP",
    "description" : "Evento de qualquer coisa",
    "image" : "https://www.formacao.dev/assets/img/formacao-dev.png",
    "bgImage" : "https://www.formacao.dev/assets/img/formacao-dev-background.png",
    "expectedAudience" : 1000,
    "guests" : [
        {
            "name" : "Ricardo Pereira",
            "email" : "patrese@example.com",
            "confirmation" : true,
            "hasCompanions" : false,
            "quantityCompanions" : 0
        }
    ]
}